#!/usr/bin/python

#
# This maintenance script updates the content of the "Orthanc" folder
# to match the latest version of the Orthanc source code.
#

import multiprocessing
import os
import stat
import urllib2

TARGET = os.path.join(os.path.dirname(__file__), 'Orthanc')
PLUGIN_SDK_VERSION = '0.9.5'
REPOSITORY = 'https://hg.orthanc-server.com/orthanc/raw-file'

FILES = [
    ('Plugins/Samples/Common/OrthancPluginCppWrapper.cpp', 'Plugins'),
    ('Plugins/Samples/Common/OrthancPluginCppWrapper.h', 'Plugins'),
    ('Plugins/Samples/Common/OrthancPluginException.h', 'Plugins'),
    ('Plugins/Samples/Common/VersionScript.map', 'Plugins'),
    ('Resources/CMake/AutoGeneratedCode.cmake', 'CMake'),
    ('Resources/CMake/Compiler.cmake', 'CMake'),
    ('Resources/CMake/DownloadPackage.cmake', 'CMake'),
    ('Resources/CMake/GoogleTestConfiguration.cmake', 'CMake'),
    ('Resources/DownloadOrthancFramework.cmake', 'CMake'),
    ('Resources/EmbedResources.py', 'CMake'),
    ('Resources/LinuxStandardBaseToolchain.cmake', 'Toolchains'),
    ('Resources/MinGW-W64-Toolchain32.cmake', 'Toolchains'),
    ('Resources/MinGW-W64-Toolchain64.cmake', 'Toolchains'),
    ('Resources/MinGWToolchain.cmake', 'Toolchains'),
]

SDK = [
    'orthanc/OrthancCPlugin.h',
]


def Download(x):
    branch = x[0]
    source = x[1]
    target = os.path.join(TARGET, x[2])
    print target

    try:
        os.makedirs(os.path.dirname(target))
    except:
        pass

    url = '%s/%s/%s' % (REPOSITORY, branch, source)

    with open(target, 'w') as f:
        f.write(urllib2.urlopen(url).read())


commands = []

for f in FILES:
    commands.append([ 'default',
                      f[0],
                      os.path.join(f[1], os.path.basename(f[0])) ])

for f in SDK:
    commands.append([
        'Orthanc-%s' % PLUGIN_SDK_VERSION, 
        'Plugins/Include/%s' % f,
        'Sdk-%s/%s' % (PLUGIN_SDK_VERSION, f) 
    ])


pool = multiprocessing.Pool(10)  # simultaneous downloads
pool.map(Download, commands)
